### ISSUE TITLE
Create generic JS helper for testing if Firefox is configured as default browser

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/bedrock#13933]
## Description

There's a few different places where we are checking if Firefox is configured as the default browser. Each uses their own custom code, or imports some older custom code (which means their check can break if the other page is removed).

If we're going to be doing this regularly we should make a library that:
1) checks if the browser is Firefox
2) check if Firefox is the default browser
3) updates the user's segment in analytics
4) adds a class to the `<body>`
5) accepts resolve and reject callbacks

Current custom code which should be updated to use the new helper:

/bedrock/media/js/firefox/family/fx-is-default.es6.js (this file is used by both family and CTD)
/bedrock/media/js/firefox/set-as-default/thanks.js
/bedrock/media/js/firefox/whatsnew/whatsnew-116-eu.js
/bedrock/media/js/firefox/whatsnew/whatsnew-118.es6.js

Suggested body classes:
`firefox-is-default` `firefox-not-default`

**Comment by stephaniehobson** [comment]
Fixed by the automatic retirement of the campaign and WNPs.

**Comment by stephaniehobson** [comment]
Fixed by the automatic retirement of the campaign and WNPs.

**Comment by alexgibson** [comment]
@stephaniehobson i think you just closed an issue that @wen-2018 is assigned to and working on?

This seems like something we’d likely use on various pages in the future still?

**Comment by wen-2018** [comment]
@alexgibson I looked into this issue last week and all the files referenced have been removed from the repo since. So it seems we don't need this helper function for now?

**Comment by alexgibson** [comment]
I still see this code being actively used in pages (the issue above only listed a few occurrences). But it looks like @reemhamz has found a nice way to make it more reusable in https://github.com/mozilla/bedrock/pull/14832.
